[package]
name = "htmlquery"
version = "0.1.0"
authors = ["Konstantin <phpconf@gmail.com>"]

[dependencies]
html5ever = "0.22.3"
hierarchy = {git = "https://github.com/Frozen/hierarchy.git", tag = "0.1.5"}
tendril = "0.4.0"
maplit = "1.0.1"
linked_hash_set = "0.1.3"

[dev-dependencies]
file = "*"
